name: build workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: setup-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true

      - run: |
          cd ./webapp/go
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o isucondition
