name: build workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: docker compose build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker compose build
        working-directory: webapp/
        run: |
          docker compose -f docker-compose-go.yml build
